# Generated by Django 5.0.6 on 2024-07-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(choices=[('USA', 'Estados Unidos'), ('Brazil', 'Brasil'), ('Other', 'Outros')], max_length=100),
        ),
    ]
